### PR TITLE
Update Nvidia Driver requirements

### PR DESCRIPTION
**Pull request by prybicki**
Bumping requirements to CUDA 11.7 (minimal version supported on Ubuntu 22)

### CODE REVIEW

**Review by shmpwk — APPROVED** [review]
thank you!

**Review by mackierx111 — APPROVED** [review]
LGTM👍

**Comment by 11Takanori** [comment]
@prybicki
Do you have any information on whether issues could occur when using Nvidia Driver versions lower than 515.43.04, or have these versions just not been tested yet?

**Comment by prybicki** [comment]
@11Takanori 
We need to use CUDA Toolkit 11.7, since it is the minimal version supported on Ubuntu 22.04. According to [the official NVIDIA sources](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id4), it requires the aforementioned driver. Since we build RGL kernels to PTX (virtual assembly for the GPU), it is compiled in the runtime, which requires a driver new enough to handle PTX generated by the 11.7 Toolkit. An older driver would most likely fail with cudaErrorUnsupportedPtxVersion.

**Pull request merged**
