### PR TITLE
Performance Improvements: Camera sensor rendering

### PR DESCRIPTION
**Pull request by pijaro**

### CODE REVIEW

**Review by mackierx111 — CHANGES_REQUESTED** [review]
@pijaro 
Thanks for the implementation. I think it is a good implementation.

I believe that CameraSensor now requires the CameraSensorHolder class (and a call to `DoRender()`), so I would like to see the documentation on camera sensors updated as well.

**Comment by pijaro** [comment]
@szylis Could you look into the documentation and update it?

**Comment by szylis** [comment]
@mackierx111 @pijaro 
I have updated documentation for CameraSensor.

**Review by mackierx111 — APPROVED** [review]
thanks! LGTM

**Comment by mackierx111** [comment]
I will resolve conflicts.

**Pull request merged**
