### PR TITLE
Performance Improvements: Objects and NPCs with occlusion culling

### PR DESCRIPTION
**Pull request by pijaro**

### CODE REVIEW

**Review by mackierx111 — CHANGES_REQUESTED** [review]
image

@pijaro 
I could not get the `AutowareSimulation.unity` scene to work correctly. Could you please tell me how to do a correct review?

**Comment by mackierx111** [comment]
@pijaro 
I tried to run the scene. Is this occlusion culling working correctly?
image
image

**Comment by mackierx111** [comment]
@pijaro 
Sorry for neglecting this pull request. Can you please resolve the conflict so I can review this pull request again and merge it into the main branch?

**Comment by lchojnack** [comment]
@mackierx111 
I've resolved conflicts. The PR is ready for review

**Comment by mackierx111** [comment]
@lchojnack 
Can you please provide me with a download link for Shinjuku with occlusion culling applied?

**Comment by lchojnack** [comment]
@mackierx111 
The unitypackage is [here](https://drive.google.com/file/d/1bqlmrueT65GBkyjLfVYXZT1f41X2nlQq/view?usp=drive_link)
I've noticed that after resolving the conflicts, the occlusion culling was not enabled. I've enebled it.

**Comment by mackierx111** [comment]
@lchojnack 
I imported the `Japan_Tokyo_Nishishinjuku_improved.unitypackage` and ran the AutowareSimulation scene.
However, some objects in nishishinjuku (Tree, fence, etc.) are not displayed. Could you please check?
Also, I would like to see the scene conflicts eliminated.

Sorry it took so much time to review this pull reqeust. But I want to check it carefully.

image

**Comment by mackierx111** [comment]
Change to draft until the above comments are resolved.

**Comment by lchojnack** [comment]
@mackierx111 
I've resolved the conflict and updated the `Nishishinjuku RandomTraffic` prefab
I've also prepared the new unitypackage which is a [unitypackge used so far](https://tier4.github.io/AWSIM/GettingStarted/SetupUnityProject/#:~:text=Download%20and%20import%20Japan_Tokyo_Nishishinjuku.unitypackage) with shrubs and trees improvements which comes with this PR.
The unitypackage is available [here](https://drive.google.com/file/d/1TSIZdQ-JFVelOJ25NSpVhmV8dpLgbcBP/view?usp=drive_link)

**Review by mackierx111 — APPROVED** [review]
LGTM! 
We plan to release v1.2.2 as soon as possible. At that time, we will also distribute the new Nishi-Shinjuku environment unitypackage.

**Pull request merged**
