### PR TITLE
Feature: Main Camera Rotate Around

### PR DESCRIPTION
**Pull request by szylis**
**Intention:**
To add functionality to the main camera - `FollowCamera.cs` script to allow the user to rotate the camera around a specific target.

**Includes:**
- refactor of the existing `FollowCamera.cs `script,
- adding a new functionality to the main camera, that allows the user to rotate the camera around the target,
- adding an optional UI View - with hints on how to use it,

**How to use:**
- camera rotation around target can be activated by pressing the 'C' key on the keyboard - text info at the top of the screen will indicate if camera is ready to be rotate,

- use the numeric keypad to control the view of the main camera, in such way:
<ul>

- 'numkey 1' - to rotate left;
- 'numkey 3' - to rotate right;
- 'numkey 2' - to set the back view;
- 'numkey 8' - to set the front view;
- 'numkey 4' - to set the left view;
- 'numkey 6' - to set the right view;

</ul>

- to switch off the camera rotate around mode, press the 'C" key again.

**Optional:**
An optional prefab with UI panel is included in this PR. This prefab can be dragged and dropped under Canvas in the scene, and it will display the key bind for the camera view, when rotate camera around is active.  The prefab can be found in: `Assets/Prefabs/UI/MainCameraView.prefab`

### CODE REVIEW

**Review by mackierx111 — CHANGES_REQUESTED** [review]
Thanks for the implementation. I have a few requests.
- Please able to move the camera with the mouse instead of using the numeric keypad to control the camera. (Mouse move to rotate camera. Mouse wheel to zoom camera)
- Please allow the inspector to assign a key to switch between rotation mode and follow mode. (Default is C.)
- Please when RotateCamera mode is off, it is better to return to the normal follow camera
- Please change the UI to match the above specifications. (MainCameraViewUI)

**Comment by szylis** [comment]
Thanks. Yes, I will do it as soon as possible.

**Comment by szylis** [comment]
I've implemented requested features. 

- so now to rotate the camera, **hold down the middle mouse button** and **move the mouse horizontally**,
- to zoom in and out - use the mouse scroll wheel,

Also the **mouse rotation sensitivity** and **mouse zoom sensitivity** can be adjusted from the inspector.

**Review by mackierx111 — CHANGES_REQUESTED** [review]
Thanks for the implementation! Just a few more improvements please.
- Please to be able to control the rotation mode of the camera view by simply dragging the mouse without having to press the mouse wheel.
- Please to be able to adjust the vertical camera position in the Y direction as well as the X direction.

**Comment by szylis** [comment]
Thanks for quick reply.

I would like to clarify your request:

> Please to be able to adjust the vertical camera position in the Y direction as well as the X direction.

Do you mean that the mouse movement should control both the Y and X axis? In that way, the vertical position of the mouse should move the camera up and down.

Or do you mean that when zooming out, the camera should also adjust the Y positions?

**Comment by szylis** [comment]
I have implemented the improvements.
- do not need to press middle mouse button to rotate,
- left-right mouse movement to rotate around,
- forward-backward mouse movement to move camera in vertical axis,

Additionally I have added:
- toggle to invert mouse movement for rotation, height and zoom.
- sliders in inspector for movement sensitivity.

**Review by mackierx111 — APPROVED** [review]
great! LGTM

**Pull request merged**
