### PR TITLE
docs(QuickStartDemo): Autoware stable branch is changed from awsim-stable to galactic

### PR DESCRIPTION
**Pull request by shmpwk**
Signed-off-by: Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>

[Autoware main branch](https://github.com/autowarefoundation/autoware/tree/main) has been updated to Ubuntu22.04 ROS 2 humble version as announced [here](https://github.com/autowarefoundation/autoware/discussions/2622#discussioncomment-4283855).
However, current AWSIM main branch is for Ubuntu20.04 ROS 2 galactic version.

Thus we should use [Autoware galactic branch](https://github.com/autowarefoundation/autoware/tree/galactic) for now.

### CODE REVIEW

**Comment by LiangHuangBC** [comment]
By current doc, I can not run quick start demo or by unity project. When will awsim upgrade to humble?

**Comment by LiangHuangBC** [comment]
Tried galactic branch of Autoware, a lot of dep issue on rosdep install.

**Comment by shmpwk** [comment]
@LiangHuangBC 

> When will awsim upgrade to humble?

January or after. Currently, only galactic is supported.


> Tried galactic branch of Autoware, a lot of dep issue on rosdep install.

Actually, galactic was EOL, so could you try this?

`rosdep update --include-eol-distros` 

For more issues, please post issue [here](https://github.com/tier4/AWSIM/issues).

**Review by mackierx111 — APPROVED** [review]
LGTM

**Pull request merged**
