### PR TITLE
feat(ros2_entity_controller): provide spawn, pose update, despawn

### PR DESCRIPTION
**Pull request by dmoszynski**
Full functionality of Ros2 Entity Controller has been provided:
- defining (using Editor) lists of Entities types: `Vehicle`, `Pedestrian`, `Object` prefabs along with specifying `AssetKey` for each of them
- subscribing to 3 different topics for: spawn, update pose and despawn
- queuing subscribed commands and executing them in the main thread (it is necessary due to the performed operations)
- spawning, updating poses and despawning based on `UniqueID`
- spawning and updating poses with coordinate system conversion (including `MGRS`)
- storing spawned entities and updating them using one list with an abstract type `Entity`
- `LogError` in case of problems with the execution of a subscribed command

The previous concept of 3 separate classes (`NPCVehiclePrefab`, `NPCPedestrianPrefab`, `TransformPrefab`) had to be changed due to the fact that only objects currently added to the scene could be added to these lists (only the script from the object added on the scene can be selected).
To solve this problem, that is, for example, to fill list `npcVehiclePrefabs` with some `NPCVehicle` prefab from outside the scene, it was necessary to use `GameObject` references.

As a result of this change, probably a limitation on the ability to add `GameObject' should be developed:
- for npcVehiclePrefabs - only assets with `NPCVehicle (script)`
- for npcPedestrianPrefabs - only  assets with  `NPCPedestrian (script)`
- to objectsPrefabs - only  assets with `Rigidbody` 

Developed ROS2 messages are available here: [entity_controller_msgs](https://drive.google.com/drive/folders/13DTKgcMPmybDrLEtrQbrje_WHaUfStjz). 
If I have to add it via PR to some repository, please let me know.

Screenshot from 2023-07-05 09-44-10

In addition, a sample scene **AWSIM/Scenes/Samples/Ros2EntityControllerSample.unity** was developed for testing purposes. 
It uses the _Ros2EntityControllerSample.cs_ script - publishing spawn, update pose and despawn messages.

Video shows how it works:

https://github.com/tier4/AWSIM/assets/121798334/486825a0-e5e4-466d-99de-f08192672c95

### CODE REVIEW

**Review by mackierx111 — CHANGES_REQUESTED** [review]
Good implementation! Here is some feedback
- Please move `Ros2EntityController.cs` and [entity_controller_msgs](https://drive.google.com/drive/folders/13DTKgcMPmybDrLEtrQbrje_WHaUfStjz) to the Assets\AWSIM\Scripts\ROS directory
- Could you please create a sample scene for Ros2EntityController in Assets\AWSIM\Scenes\Samples? I would like you to place the python or other code to manipulate the Entity and a simple instruction document in the directory of the sample scene. The content of the Ros2EntityControllerSample scene is up to you.
- If there is anything in my [commit](https://github.com/tier4/AWSIM/pull/160/commits/a8c71e161ec74394681aae6419e3522cc8b5b71d) that is not good, you are welcome to improve it.

**Comment by dmoszynski** [comment]
@mackierx111 
I've done what you asked for ([jira update](https://tier4.atlassian.net/browse/RJD-307?focusedCommentId=130430)).

**Comment by dmoszynski** [comment]
@mackierx111 
Indeed, I did not provide Windows libraries for the package - sorry for this shortcoming. 
Now they have been added, the scene has been confirmed to work properly on `Windows`:

Screenshot

**Review by mackierx111 — APPROVED** [review]
great! LGTM

**Comment by xmfcx** [comment]
Hello @dmoszynski @mackierx111 

Why was this functionality added? 

Is it to allow creating NPCs from ROS 2 messages? (Like in simple planning simulator, creating objects from RViz2)

cc. @TakaHoribe

**Comment by xmfcx** [comment]
More context:

@TakaHoribe wants the following functionalities from the [simple_planning_simulator](https://github.com/autowarefoundation/autoware.universe/tree/main/simulator/simple_planning_simulator) and [dummy_perception_publisher](https://github.com/autowarefoundation/autoware.universe/tree/main/simulator/dummy_perception_publisher):
- Spawn NPCs from RViz2
- Remove existing NPCs from RViz2
- Change the position of the ego vehicle from RViz2

It seems this PR added a scene that can achieve all these with a new custom message.

[dummy_perception_publisher](https://github.com/autowarefoundation/autoware.universe/tree/main/simulator/dummy_perception_publisher) uses [dummy_perception_publisher::msg::Object](https://github.com/autowarefoundation/autoware.universe/blob/main/simulator/dummy_perception_publisher/msg/Object.msg):
```
std_msgs/Header header
unique_identifier_msgs/UUID id
dummy_perception_publisher/InitialState initial_state
autoware_auto_perception_msgs/ObjectClassification classification
autoware_auto_perception_msgs/Shape shape
float32 max_velocity
float32 min_velocity

uint8 ADD=0
uint8 MODIFY=1
uint8 DELETE=2
uint8 DELETEALL=3
int32 action
```

Either of the following could be done to achieve the request from the planning team:
1. Make [dummy_perception_publisher](https://github.com/autowarefoundation/autoware.universe/tree/main/simulator/dummy_perception_publisher) use the new [entity_controller_msgs](https://github.com/tier4/AWSIM/tree/main/Assets/AWSIM/Scripts/ROS/entity_controller_msgs) (is this a new message type just created for this PR?)
2. Create a translation node from [dummy_perception_publisher::msg::Object](https://github.com/autowarefoundation/autoware.universe/blob/main/simulator/dummy_perception_publisher/msg/Object.msg) to [entity_controller_msgs](https://github.com/tier4/AWSIM/tree/main/Assets/AWSIM/Scripts/ROS/entity_controller_msgs)

**Pull request merged**
