### PR TITLE
feat: migrate autoware_auto_msgs to autoware_msgs

### PR DESCRIPTION
**Pull request by lchojnack**
- I’ve updated the documentation
- I’ve tested the PR with the latest Autoware and it works as expected

  [screen_recorder-2024-06-07_15.49.19.webm](https://github.com/tier4/AWSIM/assets/8416175/ca213691-aaff-4aa7-9fb2-e2b716c66047)

- I’ve tested the AWSIM on Windows without Autoware and it works as expected
  autoware_msgs_windows

- I’ve tested the AWSIM with ss2 on branch [RJD-736/autoware_msgs_support](https://github.com/tier4/scenario_simulator_v2/tree/RJD-736/autoware_msgs_support)  following [the instruction](https://tier4.github.io/AWSIM/GettingStarted/UsingOpenSCENARIO/) and it works as expected

### CODE REVIEW

**Comment by Goldob** [comment]
The branch has been updated to current main and the PR is ready for review.

**Comment by mackierx111** [comment]
I ran this branch with the awsim-stable-update branch in my local environment. As a result, Autoware was not able to use the camera image, which is under investigation.

**Comment by lchojnack** [comment]
I've updated the PR with the latest `main` branch
The PR is working with [awsim-stable-update](https://github.com/autowarefoundation/autoware/tree/awsim-stable-update)

https://github.com/user-attachments/assets/e459bdfc-e72d-4c20-9e59-db3b457027a2

**Comment by mackierx111** [comment]
I have completed checking this pull request.
but I had to follow a few steps, which I will note here.

1. Run setup-dev-env.sh with awsim-stable-update branch. (all yes)
2. Install nvidia-driver-550 in Additional Driver -> Software & Updates and lower the version from 560
3. Apply two PRs to Autoware. [#8663 fix(reaction_analyzer): fix include hierarchy of tf2_eigen](https://github.com/autowarefoundation/autoware.universe/pull/8663), [#196 fix(nebula_hw_interfaces): add missing iomanip header](https://github.com/tier4/nebula/pull/196)
4. Then build Autoware as usual.

**Comment by mackierx111** [comment]
image (43)

It no longer outputs more than **15 km/h**. I am asking the Autoware developer if this is intentional.

**Comment by mackierx111** [comment]
It was intentional.
https://github.com/autowarefoundation/autoware_launch/pull/763

**Review by mackierx111 — APPROVED** [review]
LGTM!

**Pull request merged**
